:Author: vansh3022
:Email:
:Date: 22/09/2021
:Revision: version#
:License: Public Domain

= Project: SIT210-Task3.1-Arduino-IoT-Cloud

Real-Time Temperature Monitor with Temperature Indicator

== Step 1: Installation
Connect the DHT22 sensor to the Nano 33 IoT according to the sketch uploaded on Arduino IOT Cloud and provide a network connection to show real-time changes in data on the dashboard 

For example:

1. Open this file
2. Refer to the Pictures for the connections
3. Build the dashboard taking reference of the Picture above  

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 SIT210-Task3.1P-Ardunio-IoT-Cloud                => Arduino sketch folder
  ├── sketch123.ino                               => main Arduino file
  ├── arduino_secrets.h                           => file for setting up the network connection
  ├── thingProperties.h                           => necessary file for code to work
  ├── Dashboard.png                               => An image of the Dashboard
  ├── Layout.jfif                                 => An image of the circuit layout
  └── ReadMe.adoc                                 => Method to work with the files
....

=== License
This project is released under a Public License.

=== Contributing
To contribute to this project please contact: 9996250931 

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name          | Part number | Quantity
| U1 | Usb Cable          | UCX00066    | 1
| A1 | Arduino Nano33IoT  | ANX00066    | 1
| B1 | Breadboard(any)    | BBX00066    | 1
| J1 | Jumper Wires       | JWX00066    | 3
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
